### ISSUE TITLE
Searching in the example code does not work 

### ISSUE THREAD

**Issue by sasan-ai** [vdaas/vald-client-python#5]
Hello,

I was trying to run the provided example against a vald instance installed in a k8s cluster. 

While Insert, Update, and Remove works as expected, I'm getting the following error for search:

Command: 
scfg = payload_pb2.Search.Config(num=100, radius=-1.0, epsilon=0.01, timeout=3000000000)
res = sstub.Search(payload_pb2.Search.Request(vector=[0.2, 0.2, 0.3], config=scfg))

Error:

`---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
<ipython-input-15-6511a7036367> in <module>
      1 scfg = payload_pb2.Search.Config(num=100, radius=-1.0, epsilon=0.01, timeout=3000000000)
----> 2 res = sstub.Search(payload_pb2.Search.Request(vector=[0.2, 0.2, 0.3], config=scfg))

~/anaconda3/lib/python3.8/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    921         state, call, = self._blocking(request, timeout, metadata, credentials,
    922                                       wait_for_ready, compression)
--> 923         return _end_unary_response_blocking(state, call, False, None)
    924 
    925     def with_call(self,

~/anaconda3/lib/python3.8/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    824             return state.response
    825     else:
--> 826         raise _InactiveRpcError(state)
    827 
    828 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Search API failed to process search request"
	debug_error_string = "{"created":"@1613339575.111192823","description":"Error received from peer ipv4:10.30.241.242:8081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Search API failed to process search request","grpc_status":13}"
>`

**Comment by rinx** [comment]
Sorry for belated response.
The problem still happens in your environment?
